image: node:latest
# On déclare une image de base ici une image contenant la derniere version de Nodejs
cache:
  paths:
    - node_modules/
# On ajoute un cache qui indique les fichiers qui doivent être sauvegarder.
stages:
  - test
# On définie les différents processus qui seront exécuter
testing_testing:
  stage: test
  script:
    - npm install
    - npm test
# On lance la commande pour installer les dépendances puis on lance la commande de test
